version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV=production
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]